### ISSUE TITLE
ros-indigo-sophus debian package

### ISSUE THREAD

**Issue by aeudes** [stonier/sophus#1]
I have an issue with the sophus ros package.
I have install the package on ubuntu but catkin could not find it. It complains that sophusConfig.cmake didn't exist.

 I have check the package and the file exist but it seems to me that the file is in the wrong directory. The package export a cmake directory in package.xml but this directory did not exist in the released package. Finally, moving the sophusConfig.cmake file to a new cmake directory solve the problem. 
Could you fix that upstream ?

**Comment by stonier** [comment]
Not sure I'm following you with this one. Works for us no problem, so question is to track down what we're doing differently from each other.

Which directory did you move the file to?

What export are you referring to in `package.xml`? The following...?

```
<export>
  <build_type>cmake</build_type>
</export>
```

This tag is just to help the build farm recognise it as a cmake 3rd party project.

**Comment by stonier** [comment]
I wonder if you're missing something in your package that is trying to find sophus. Some examples for you from one of my packages. In `package.xml`:

```

  <build_depend>ecl_linear_algebra</build_depend>
  <build_depend>ecl_time</build_depend>
  <build_depend>sophus</build_depend>
  <build_depend>dslam_common</build_depend>


  <run_depend>ecl_linear_algebra</run_depend>
  <run_depend>ecl_time</run_depend>
  <run_depend>sophus</run_depend>
  <run_depend>dslam_common</run_depend>
```

and in `CMakeLists.txt`:

```
find_package(catkin REQUIRED COMPONENTS                                   
                 ecl_linear_algebra
                 ecl_time 
                 dslam_common
                 )
find_package(sophus REQUIRED)

catkin_package(
    INCLUDE_DIRS include 
    LIBRARIES ${PROJECT_NAME}
    DEPENDS                
        sophus
    CATKIN_DEPENDS                
        ecl_linear_algebra
        ecl_time
        dslam_common
    )
```

**Comment by aeudes** [comment]
Ok, the main difference is that I find_package sophus as a catkin package with :

```
find_package(catkin REQUIRED COMPONENTS                                   
                 ecl_linear_algebra
                 ecl_time 
                 dslam_common
                 sophus
                 )
```

In this case catkin did not find sophus.
I now see the difference between thirdparty/catkin package.

Because if you move the sophus cmake config file in a cmake directory in the package :

```
/opt/ros/indigo/share/sophus/package.xml
/opt/ros/indigo/share/sophus/sophusConfig.cmake
```

to 

```
/opt/ros/indigo/share/sophus/package.xml
/opt/ros/indigo/share/sophus/cmake/sophusConfig.cmake
```

both import worked...

Thank you very much for your concern and quick answer. I will change the way I am making the importing sophus.

**Comment by stonier** [comment]
I think alot of people run into this trouble as the differences are subtle. While it could be argued that bloom should put the config in the cmake folder to relax the syntax, that would have to get into `bloom`. 

At the least, I put the syntax examples above on the [sophus wiki page](http://wiki.ros.org/sophus). Hopefully that'll help out the next person.
