### ISSUE TITLE
Recent change to pure cmake causes build issues

### ISSUE THREAD

**Issue by clalancette** [stonier/sophus#15]
Commit 45bd7d75b0d748b5ba6f35822b0110fcec65253c changed this package to be a pure cmake one (instead of an ament_cmake one).  With that change, I can no longer build downstream consumers of this library (like `ecl_core/ecl_linear_algebra`).  When I do try to build, I get the following error:

```
In file included from /home/ubuntu/ros2_ws/src/ecl_core/ecl_linear_algebra/src/lib/sophus_helpers.cpp:10:0:
/home/ubuntu/ros2_ws/src/ecl_core/ecl_linear_algebra/src/lib/../../include/ecl/linear_algebra/sophus/helpers.hpp:25:26: fatal error: sophus/se3.hpp: No such file or directory
compilation terminated.
```

Looking at the build command, it looks like this:

```
cd /home/ubuntu/ros2_ws/build_isolated/ecl_linear_algebra/src/lib && /usr/bin/c++   -DROS_PACKAGE_NAME=\"ecl_linear_algebra\" -Decl_linear_algebra_EXPORTS -isystem /home/ubuntu/ros2_ws/install_isolated/ecl_eigen/include -isystem /usr/include/eigen3 -isystem /home/ubuntu/ros2_ws/install_isolated/ecl_exceptions/include -isystem /home/ubuntu/ros2_ws/install_isolated/ecl_config/include -isystem /home/ubuntu/ros2_ws/install_isolated/ecl_errors/include -isystem /home/ubuntu/ros2_ws/install_isolated/ecl_formatters/include -isystem /home/ubuntu/ros2_ws/install_isolated/ecl_converters/include -isystem /home/ubuntu/ros2_ws/install_isolated/ecl_concepts/include -isystem /home/ubuntu/ros2_ws/install_isolated/ecl_type_traits/include -isystem /home/ubuntu/ros2_ws/install_isolated/ecl_mpl/include -isystem /home/ubuntu/ros2_ws/install_isolated/ecl_math/include  -std=c++14 -Wall -Wextra -Wl,--no-as-needed -fPIC   -std=gnu++11 -o CMakeFiles/ecl_linear_algebra.dir/sophus_helpers.cpp.o -c /home/ubuntu/ros2_ws/src/ecl_core/ecl_linear_algebra/src/lib/sophus_helpers.cpp
```

If you look closely, you'll notice that it has no reference to the include paths for sophus (in this case, it would be something like `install_isolated/sophus/include/sophus/se3.hpp`).  I think that the sophus package needs to export the include directories from its `.cmake` files so that downstream users can consume them (alternatively, it could be that `ecl_core` has to explicitly include the directories).

**Comment by stonier** [comment]
I think I saw the same build error and switched to using the imported target with this pull request: https://github.com/stonier/ecl_core/pull/70/files#diff-70b3885401cd3232ac3149ca2e16e066R27

Re-open this if it's still an issue for you.

**Comment by stonier** [comment]
Checked the dates, something seemed off, tested locally, and reproduced....

Reopening!

**Comment by stonier** [comment]
Dropping into `ecl_linear_algebra`:

```
get_target_property(IMPORTED_INCLUDE_DIRS Sophus::Sophus INTERFACE_INCLUDE_DIRECTORIES)
message(FATAL_ERROR "Sophus_INCLUDE_DIRS......${IMPORTED_INCLUDE_DIRS}")
```
yields
```
CMake Error at src/lib/CMakeLists.txt:32 (message):
  Sophus_INCLUDE_DIRS....../usr/include/eigen3
```

Definitely looks like Sophus is not exporting it's own include directories.

**Comment by stonier** [comment]
Odd, single package build of sophus creates the correct sophusTargets.cmake:

```
ament build
  --isolated
  --symlink-install
  --build-tests
  --only-packages sophus
  --force-ament-cmake-configure --cmake-args
  -DCMAKE_BUILD_TYPE=RelWithDebInfo
  -DCMAKE_VERBOSE_MAKEFILE:=ON
```
where the all important line is in the targets module is (_IMPORT_PREFIX  bit):

```
set_target_properties(Sophus::Sophus PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_auto_type;cxx_decltype;cxx_nullptr;cxx_right_angle_brackets;cxx_variadic_macros;cxx_variadic_templates"
  INTERFACE_INCLUDE_DIRECTORIES "/usr/include/eigen3;${_IMPORT_PREFIX}/include"
  INTERFACE_SYSTEM_INCLUDE_DIRECTORIES "/usr/include/eigen3"
)
```

but a larger ament_cmake build loses the appended _IMPORT_PREFIX bit.

**Comment by stonier** [comment]
Simple bug, GNUInstallDirs wasn't called early enough.

* Upstream PR: https://github.com/strasdat/Sophus/pull/161
* Local commit: fe7d0883
