### ISSUE TITLE
ros-noetic-sophus not in apt list

### ISSUE THREAD

**Issue by tadteo** [stonier/sophus#19]
I'm trying to install ros-noetic-sophus from apt but it cannot find the package.
Other packages from noetic are available and normally installed but unfortunately, Sophus is not available. However here https://index.ros.org/p/sophus/github-stonier-sophus/#noetic it says that should be available. 
My question than is is it actually available or not??

**Comment by stonier** [comment]
http://repositories.ros.org/status_page/ros_noetic_default.html?q=sophus

You can see they've been bloomed and added to rosdistro, but failing on the jenkins job. That's probably why the index is stretching the truth for you :)

Looks like noetic builds on CI have become stricter. I suspect (not 100% sure on this) that it is their  CI using more aggressive compiler flags (warnings as errors), I believe they're doing this for ros2 builds and so just introducing this back in ros1 builds for noetic. 

At any rate, I'm in the middle of updating a laptop to noetic so I can test, so it should be not far away. In the meantime, I've heard from other users that they got the release/1.1.x branch working locally.

**Comment by tadteo** [comment]
Ok good. Then how can I build and install it from source? On the code, I don't find it.
Thanks for your help

**Comment by stonier** [comment]
Re-synced with upstream (where bugs were fixed). 1.2.x versions on their way. 

* Noetic: https://github.com/ros/rosdistro/pull/25830
* Foxy: https://github.com/ros/rosdistro/pull/25831

Apologies for missing your question. Building it from source is like any other package. Just drop the relevant branch (see the [README](https://github.com/stonier/sophus/blob/readme/README.md) for links) in your workspace.
