### ISSUE TITLE
ECCN for Sophus

### ISSUE THREAD

**Issue by Likhitha2809** [stonier/sophus#20]
Hi, For documentation purpose and project release process we need the Export control classification number(ECCN) for Sophus if it applies. Can you please let me know the ECCN ?

**Comment by stonier** [comment]
As far as I know, open source projects don't come under export controls ([here](https://www.linuxfoundation.org/blog/2020/07/understanding-us-export-controls-with-open-source-projects/)). I'm no expert though and if you want to pursue it farther, check in with the upstream project. This project here is just a maintainer fork.
