### ISSUE TITLE
cmake find package can not find this

### ISSUE THREAD

**Issue by ghost** [stonier/sophus#21]
I have downloaded this repo, built it, and ran "sudo make install". 

However, when I tried to use it in my project, it always complained 

fatal error: sophus/so3.h: No such file or directory
 #include "sophus/so3.h"

Below is my CMakeList.txt

cmake_minimum_required( VERSION 2.8 )
project( useSophus )

find_package( Sophus REQUIRED)
include_directories( ${Sophus_INCLUDE_DIRS} )
include_directories( "/usr/include/eigen3" )

add_executable( useSophus useSophus.cpp )

target_link_libraries( useSophus ${Sophus_LIBRARIES} )
~

**Comment by stonier** [comment]
You're using a legacy CMake v2 approach. I haven't done this for a while, and it looks like they don't support a v2 approach any longer. Essentially this means there is no fudging around with `${Sophus_INCLUDE_DIRS}` and `${Sophus_LIBRARIES}` any longer. You'll want something like:

```
find_package(Sophus REQUIRED)

add_executable( useSophus useSophus.cpp )
target_link_libraries(
  useSophus
  PUBLIC
    Sophus::Sophus
)
```

That imported `Sophus::Sophus` target should take care of it all for you.
