### ISSUE TITLE
ROS Kinetic Debian Package doesn't seem to work?

### ISSUE THREAD

**Issue by atomoclast** [stonier/sophus#7]
Hello, 

I am trying to build a ROS package with a dependency on Sophs and it keeps failing. I tried to use `apt` to install the Debian package of Sophus for Kinetic, and it keeps failing because it can't find the CMake file for Sophus. Then I tried to install it using the instructions in your `README` from source, and it installed fine but keeps failing as follows: 

```
fatal error: sophus/se3.h: No such file or directory
compilation terminated.
```

Not sure what the issue is, but please advise.

**Comment by stonier** [comment]
Testing it with [sophus_ros_toolkit](https://github.com/stonier/sophus_ros_toolkit) (which explicitly does use [sophus/se3.h](https://github.com/stonier/sophus_ros_toolkit/blob/devel/sophus_ros_conversions/include/sophus_ros_conversions/geometry.hpp#L18) against both the deb and the sources works fine on Kinetic/Xenial.

Can you check your package's `CMakeLists.txt` against that of [sophus_ros_toolkit](https://github.com/stonier/sophus_ros_toolkit) to make sure it is similar?

**Comment by stonier** [comment]
Been a while and likely a user's environment issue. Closing. Reopen if necessary.
