### ISSUE TITLE
Request for a ros2-ardent branch

### ISSUE THREAD

**Issue by fmrico** [stonier/sophus#9]
Hi,

It would be nice to have a ros2-ardent branch to integrate PR for ros2, as #8 

Best

**Comment by stonier** [comment]
Thinking of bumping the sophus release for ardent to match the latest upstream. Do you have any requirements one way or the other?

**Comment by stonier** [comment]
Updated for ament in #11. I'll followup with an update to upstream sometime soon.

**Comment by fmrico** [comment]
@stonier Thanks!!
